/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_rhko5jrgyuzakebsyucei2dkva/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
